[package]
name = "guessing_game"
version = "0.1.0"
authors = ["Nuno Barreto <nuno.barreto@inventsys.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.0"
