[package]
name = "yew-app"
version = "0.1.0"
authors = ["Nuno Barreto <nbarreto@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.18.0"
wasm-bindgen = "0.2.67"
